### PR TITLE
feat: add Haiku to the operating systems section

### PR DESCRIPTION
**Pull request by rjzak**
# RISC-V Landscape | Pre-submission checklist:

> NOTE: Please ensure you've completed each of these items after submitting your pull request:

* [X] Have you included a repo_url? Please select the most suitable GitHub repository for your project, rather than a GitHub organization.
* [X] Is your project open source?
* [X] Is the project currently and actively maintained (e.g., accepts pull requests, responds to issues)?
* [X] Have you chosen the most appropriate (existing) category for your project?
* [X] Does your submission adhere to the other guidelines from the new entries section?
* [X] Have you added your logo's SVG to the hosted_logos directory and referenced it in the landscape.yml entry?
* [X] Does your logo clearly display the project/product name and follow the other logo guidelines?
* [X]  Does the project name correspond with the text on the logo?
* [X] Have you verified the accuracy of the Crunchbase data for your organization, including headquarters and LinkedIn?
* [X] Approximately 5 minutes after opening the pull request, the RISC-V_Bot will post the URL for your staging server. Have you reviewed the site, confirmed it appears as expected, and then added a comment to the PR stating "LGTM"?

### CODE REVIEW

**Comment by bprestonlf** [comment]
@andyjohnstonmoore + @rpsene - Please review proposed listing / category assignment

**Review by rpsene — APPROVED** [review]
@bprestonlf we are good to go. It has support for RISC-V via qemu.

**Comment by rjzak** [comment]
Haiku also runs on RISC-V hardware ([images](https://download.haiku-os.org/nightly-images/riscv64/)):
- [Unmatched](https://discuss.haiku-os.org/t/my-progress-on-real-risc-v-hardware/10963/31?u=rjzak)
- [Vision Five 2](https://discuss.haiku-os.org/t/progress-on-running-haiku-on-visionfive-2/13369/19?u=rjzak)

I'm working on getting a better logo, then I'll mark the PR as ready.

**Comment by rjzak** [comment]
Why can't Haiku have a link to the Haiku ports repo https://github.com/haikuports/haikuports/? Either with or without the ending slash has the same error. Is it upset about the different organisation name?

`FATAL: item Haiku has an invalid repo https://github.com/haikuports/haikuports/`

**Comment by rjzak** [comment]
LGTM

**Pull request merged**
