### PR TITLE
Add the capability to build and run from a container

### PR DESCRIPTION
**Pull request by rpsene**
This commit adds the capability to build and run the RISC-V Landscape from within a container.

Signed-off-by: Rafael Sene <rafael@riscv.org>

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
Just for your information, it relies on `weblandscapes.ddns.net` to build and compile everything

**Comment by AndreyKozlov1984** [comment]
And it was designed to run on everything above v14 or even v13 without any setup. Anyway, that is a good wrapper for those who don't want to install node.js locally

**Comment by bprestonlf** [comment]
+1

**Review by bprestonlf — APPROVED** [review]
+1 LGTM

**Comment by rpsene** [comment]
@AndreyKozlov1984 yep, the goal is make life easier when testing locally.

**Pull request merged**
